config/routes.rb
Mesmeride::Application.routes.draw do

  match '/auth/:provider/callback', :to => 'sessions#create', via: 'get'
  root 'static_pages#home'
  resources :sessions, only: [:create, :destroy]
  resources :strava_activities, only: [:create]
  resources :routes do
    resources :waypoints, only: [:index, :create, :destroy]
  end
  resources :route_images, only: [:show, :destroy]

  match '/route_images/:id/download', :to => 'route_images#download', via: 'get'
  
  match '/routes/:id/image_save', :to => 'routes#image_save', via: 'post'
  match '/routes/:id/image_permalink', :to => 'routes#image_permalink', via: 'post'
  
  match '/get_activity',  to: 'strava_activities#new', via: 'get'
  
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signin',  to: 'static_pages#signin', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/fb_channel', to: 'static_pages#fb_channel', via: 'get'
  

  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @routes = Route.where(:user_id => @current_user.id).all # find_all_by_user_id(@current_user.id)
      # render :text => @routes.inspect
    end
  end

  def help
  end

  def about
  end
  
  def contact
  end
  
  def fb_channel
    render :text => '<script src="//connect.facebook.net/en_US/all.js"></script>'
  end
  
  def signin
    redirect_to '/auth/strava'
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About Mesmeride') %>
<h1>About Mesmeride</h1>
<p>
   Mesmeride is an application to create beautiful elevation 
   profiles for Strava rides (and later, maps, and routes and segments). 
   These maps and elevation profiles can be saved as images to print or 
   share on the web. 
</p>
<p>
  The initial release replicates most of the <a href='http://marc.durdin.net/2013/07/giro-your-strava-updated-to-give-le-tour-treatment-to-the-climbs/' target='_blank'>Giro-Your-Strava bookmarklet</a> functionality, with a little bit of extra control.  
  I hope to add other styles and controls with the base that this project provides.
</p>
<p>
  This project was whipped up in Ruby on Rails over a few days in my first real holiday in years (between bike rides) as my way of
  learning some new languages, frameworks and set of tools -- <a href='http://rubyonrails.org/' target='_blank'>Ruby on Rails</a>, 
  <a target='_blank' href='http://coffeescript.org/'>CoffeeScript</a>, <a  target='_blank' href='http://sass-lang.com/'>Sass</a>,
  <a target='_blank' href='http://heroku.com'>Heroku</a> and more.  
</p>
<p>
  At the end of this experience, I can definitely say that coding in this new world is a wonderful way to detox after PHP, although I ended up 
  skipping most of my TDD due to (a) laziness, and (b) a desire to get something online before I ran out of holidays.  The only time
  I found myself grimacing was when I encountered <a href='http://staal.io/blog/2013/01/18/dangers-of-turbolinks/' target='_blank'>TurboLinks</a>.
  These really do break quite a few "standard" things and are a bit of a quagmire for the unwary.
</p>
<p>
  The source is all available on <a href='https://github.com/mcdurdin/mesmeride'>Github</a> but you won't be able to work with it
  without a Strava V3 API key.  That said, contributions will be gratefully reviewed and maybe even accepted!  Especially if they
  relate to a hack job I've done in not learning these tools properly.
</p>
<%= image_tag 'about_image.jpg', :title => "I'm in the Strava gear; Hell of the South race, B grade, 2013" %>
<p><a href='http://www.tasmanianphotos.ifp3.com/' target='_blank'>Photo courtesy of Clive Roper</a></p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Mesmeride on <a href="http://twitter.com/mesmeride/">Twitter</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  Try <a href='http://twitter.com/mesmeride' target='_blank'>Twitter</a> or <a href='http://facebook.com/mesmeride' target='_blank'>Facebook</a>.  No promises :)
</p>

app/views/static_pages/home.html.erb
<% if signed_in? %>
  <div class="center hero-unit">
    <h1><%= image_tag "logo-120.png", :alt => "Mesmeride", :id => 'logo-big' %></h1>
    
    <h2>Your Routes</h2>
    <div id='route-list'>
      <% if !@routes.nil? %>
        <%= render "routes/index" %>
        <!--  will_paginate @routes -->
      <% else %>
        No routes.
      <% end %>
    </div>
    
    <%= link_to "Import Strava Activity", get_activity_path %>
  </div>
<% else %>
  <div class="center hero-unit">
    <h1><%= image_tag "logo-120.png", :alt => "Mesmeride", :id => 'logo-big' %></h1>

    <h2>
      Create beautiful elevation profiles and maps for Strava activities, segments and efforts!
    </h2>

    <%= link_to "Sign in with Strava", signin_path, class: "btn btn-large btn-primary" %>
  </div>
<% end %>