config/routes.rb
Mesmeride::Application.routes.draw do

  match '/auth/:provider/callback', :to => 'sessions#create', via: 'get'
  root 'static_pages#home'
  resources :sessions, only: [:create, :destroy]
  resources :strava_activities, only: [:create]
  resources :routes do
    resources :waypoints, only: [:index, :create, :destroy]
  end
  resources :route_images, only: [:show, :destroy]

  match '/route_images/:id/download', :to => 'route_images#download', via: 'get'
  
  match '/routes/:id/image_save', :to => 'routes#image_save', via: 'post'
  match '/routes/:id/image_permalink', :to => 'routes#image_permalink', via: 'post'
  
  match '/get_activity',  to: 'strava_activities#new', via: 'get'
  
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signin',  to: 'static_pages#signin', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/fb_channel', to: 'static_pages#fb_channel', via: 'get'
  

  

end

app/models/route.rb
class Route < ActiveRecord::Base
  belongs_to :user
  has_many :waypoints, dependent: :destroy
  has_many :route_images, dependent: :destroy
  accepts_nested_attributes_for :waypoints, :allow_destroy => true
  
  def self.import_from_activity(activity_id, user_id, effort_id)
    activity = StravaActivity.find_by_activity_id(activity_id)
    
    @route = Route.create(
      :name => activity.name, 
      :source => "StravaActivity", 
      :source_id => activity_id, 
      :user_id => user_id, 
      :zoom => 25, 
      :x_scale => 25, 
      :y_scale => 25, 
      :renderer => if effort_id.nil? then "Giro" else "Le Tour" end
    )

    start_date = DateTime.iso8601(activity.data["activity"]["start_date"]).to_i

    # Import stream data
    
    streams = {}
    
    activity.data["streams"].each do |s|
      streams[s["type"]] = s["data"]
    end
    
    @route.streams = streams.to_json
    
    #
    # Count segments that qualify
    #
    
    segment_count = activity.data["activity"]["segment_efforts"].find_all { |e| e["segment"]["climb_category"] != 0 }.size

    #
    # Create segments
    #
    
    i = 0

    activity.data["activity"]["segment_efforts"].each do |e|

      segment_start_date = DateTime.iso8601(e["start_date"]).to_i

      segment_start_index = streams["time"].find_index do |t|
        t + start_date >= segment_start_date
      end

      segment_stop_index = streams["time"].find_index do |t|
        t + start_date >= segment_start_date + e["elapsed_time"]
      end

      if e["segment"]["climb_category"] != 0
        @route.waypoints.create(:name => e["name"], :distance => streams["distance"][segment_stop_index], :elevation => streams["altitude"][segment_stop_index])
        i = i + 1
      end
      
      #
      # Crop to a specific effort (any effort, not just climbs)
      #
      
      if e["id"].to_s() == effort_id
        @route.name = e["name"]
        @route.crop_start_distance = streams["distance"][segment_start_index]
        @route.crop_stop_distance = streams["distance"][segment_stop_index]
      end
    end
    
    @route.save
    
    @route
  end
end

app/controllers/routes_controller.rb
require 'tempfile'

class RoutesController < ApplicationController
  before_action :signed_in_user
  
  def index
  end

  def show
  end

  def new
    if params[:effort_id].nil?
      @route = Route.new :source => "StravaActivity", :source_id => params[:activity_id], :user_id => current_user.id, :zoom => 25, :x_scale => 25, :y_scale => 25
    else
      @route = Route.new :source => "StravaEffort[#{params[:effort_id]}]", :source_id => params[:activity_id], :user_id => current_user.id, :zoom => 25, :x_scale => 25, :y_scale => 25
    end
  end
  
  def create
    strava_effort = params[:route][:source].match /^StravaEffort\[(\d+)\]$/
    if !strava_effort.nil? || params[:route][:source] == "StravaActivity"
      if !strava_effort.nil? 
        effort_id = strava_effort[1]
      else
        effort_id = nil
      end
      
      # return render :text => effort_id
            
      # Import the route from strava activity
      @route = Route.import_from_activity(params[:route][:source_id], current_user.id, effort_id)
    end
    
    redirect_to edit_route_path(:id => @route.id)
  end

  def edit
    @route = Route.find(params[:id])
    #@route.waypoints.
    # render :text => @route.waypoints.inspect
  end

  def update
    # waypoints = JSON.parse(params[:waypoints_field])
    # render :text => params.inspect
    @route = Route.find(params[:id])
    if @route.update_attributes(route_params)
      flash[:notice] = "Route saved."
      redirect_to edit_route_path(:id => @route.id)
    else
      render :action => 'edit'
    end    
  end

  def destroy
  end
  
  def image_save
    # data:image/png;base64,
    data = params[:data]
    data = params[:data].match(/^data\:(.+?);base64,(.+)$/)
    
    name = params[:name].gsub(/[^a-zA-Z0-9_. -]/, '') + '.png'
    
    response.headers['Content-Type'] = data[1]
    response.headers['Content-Disposition'] = "attachment; filename=\"#{name}\""
    
    render :text => Base64.decode64(data[2])
  end
  
  def image_permalink
    @route = Route.find(params[:id])
    
    if @route.route_images.length >= RouteImage::MAX_IMAGES_PER_ROUTE
      render :text => [
        :error => "You can only save at most #{RouteImage::MAX_IMAGES_PER_ROUTE} images per route."
      ].to_json
      # , :status => 403, :layout => false
      return
    end

    data = params[:data]
    data = params[:data].match(/^data\:(.+?);base64,(.+)$/)
    
    name = params[:name].gsub(/[^a-zA-Z0-9_. -]/, '') # + '.png'

 
    Tempfile.open([name, '.png']) do |f|
      f.binmode
      f.write Base64.decode64(data[2])
      f.rewind
      
      @route_image = RouteImage.create(:route_id => @route.id, :image => f)
      @route_image.save!
    end
    
    
#  @route_image.download_url = object.url_for(:read,
#    :response_content_disposition => "attachment; filename=#{name}").to_s
#  @route_image.save!
                   
    
    render :partial => 'route_image', :locals => { :route_image => @route_image }
#    render :text => [
#      :route_image_id => @route_image.id, 
#      :url => @route_image.image.url, 
#      :url_small => @route_image.image.url(:small),
#      :url_download => download_url
#      ].to_json
  end
  
  private
  
    def route_params
      params.require(:route).permit(
        :name, :x_scale, :y_scale, :zoom, :renderer, :renderer_options, :crop_start_distance, :crop_stop_distance,
        waypoints_attributes: [ :id, :name, :distance, :elevation, :_destroy ]
      )
    end
    
    def signed_in_user
      redirect_to root_url, notice: "Please sign in." unless signed_in?
    end
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/views/routes/_image_save.html.erb
  <%= form_tag 'image_permalink', :id => 'image_save', :remote => true do %>
    <%= hidden_field_tag :id, @route.id %>
    <%= text_area_tag :data %>
    <%= text_field_tag :name %>
  <% end %>

  <div id='save-form' title='Share this image'>
    <div class="alert">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      You can store at most three images for each route.  Once you delete them, they're gone forever.
    </div>
    
    <ul class='thumbnails' id='save-thumbs'>
      <% @route.route_images.each do |route_image| %>
        <%= render :partial => 'route_image', :locals => { :route_image => route_image } %>
      <% end %><li id='new-thumbnail'>
        <div class='thumbnail'>
          <span>Save current design for sharing</span>
        </div>
      </li>
    </ul>
  </div>
  
  <div id='embed-form' title='Embed this image'>
    <p>Copy the following code and paste it into the HTML view of your blog post or web page</p>
    
    <textarea cols='40' rows='2'></textarea>
  </div>
  

app/views/routes/_index.html.erb
<ol class="routes">
  <%= render @routes %>
</ol>

app/views/routes/_route.html.erb
<li><%= link_to route.name, edit_route_path(route) %></li>

app/views/routes/_route_image.html.erb
<li>
  <div class='thumbnail' data-id='<%= route_image.id %>'>
    <button class='close' type='button'>&times;</button>
    <div class='thumbholder'>
      <img data-src="holder.js/150x150" alt="" src="<%= route_image.image.url(:small) %>" />
    </div>
    
    <%= button_to 'delete', {:controller => :route_images, :action => 'destroy', :id => route_image.id }, :method => 'delete', :remote => true %>

    <div class='thumbcommands' data-img='<%= route_image.image.url %>' data-alt='<%= @route.name %>' data-src='<%= route_image_url(route_image.id) %>'>
      <a href="https://twitter.com/share" class="twitter-share-button" data-url="<%= route_image_url(route_image.id) %>" data-text="Check out the hills I climbed, made beautiful with www.mesmeride.com" data-via="mesmeride" data-count="none">Tweet</a>
      <%= button_tag '', :class => 'share-to-facebook', :type => 'button' %><br/>
      <%= button_tag '', :class => 'share-to-blog', :type => 'button' %>
      <%= button_to '', {:controller => :route_images, :action => 'download', :id => route_image.id }, :method => 'get', :class => 'share-download' %>
    </div>
  </div>
</li>

app/views/routes/_tools.html.erb
<div class='footdiv' id='tools'>
  <h3>Tools</h3>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <table>
    <tr>
      <% r = if rand <= 0.5 then ['Little','Big'] else ['Teensy','Ginormous'] end %>
      <td id='size-little'><%= r[0] %></td>
      <td>
        <%= f.hidden_field :zoom %>
        <div class='size-slider' id='zoom-slider' data-value='<%= f.object.zoom %>'></div>
      </td>
      <td id='size-big'><%= r[1] %></td>
    </tr>
    <tr>
      <% r = if rand <= 0.5 then ['Quick spin','Epic'] else ['Shopping trip','Grand tour'] end %>
      <td id-'x-quick'><%= r[0] %></td>
      <td>
        <%= f.hidden_field :x_scale %>
        <div class='size-slider' id='scale-slider' data-value='<%= f.object.x_scale %>'></div>
      </td>
      <td id='x-epic'><%= r[1] %></td>
    </tr>
    <tr>
      <% r = if rand <= 0.5 then ['Molehills','Mountains'] else ['Netherlands','Switzerland'] end %>
      <td id='y-molehills'><%= r[0] %></td>
      <td><%= f.hidden_field :y_scale %><div class='size-slider' id='y-slider' data-value='<%= f.object.y_scale %>'></div></td>
      <td id='y-mountains'><%= r[1] %></td>
    </tr>
    <tr>
      <td id='crop'>Crop Ride</td>
      <td>
        <%= f.hidden_field :crop_start_distance %><%= f.hidden_field :crop_stop_distance %>
        <div class='size-slider' id='crop-slider' data-start='<%= f.object.crop_start_distance %>' data-stop='<%= f.object.crop_stop_distance %>'></div>
      </td>
    </tr>
    
  </table>
</div>
<div class='footdiv' id='controls'>
  <h3>Controls</h3>
  <div>
    <%= f.label :renderer %>
    <%= f.select :renderer, ["Giro", "Hobart 10,000 Banner", "Le Tour"] %>
  </div>
  <div><%= button_tag "Share", :id => 'share-button', :type => 'button', :class => 'btn btn-primary' %> (<span id='dimensions'>0 x 0</span>)</div>
  <div><%= button_tag "Save Route", :id => 'save-button', :type => 'button', :class => 'btn btn-small' %></div>
</div>
<div class='footdiv renderer-controls' id='h10kbanner-renderer-controls'>
  <h3>Renderer</h3>
  <%= f.hidden_field :renderer_options %>
  <div><%= select_tag 'h10k_color', "<option value='red'>Red</option><option value='green'>Green</option><option value='blue'>Blue</option>".html_safe %></div>
</div>

app/views/routes/_waypoint.html.erb
<tr data-id='<%= f.object.id %>'>
  <td>
    <%= f.hidden_field :id %>
    <%= f.hidden_field :distance %>
    <%= f.hidden_field :elevation %>
    <%= f.hidden_field :_destroy, :class => 'input-destroy' %>
    <%= f.text_field :name %>
  </td>
  <td>
    <div class='waypoint-distance'></div>
  </td>
  <td>
    <%= button_tag "×", :type => 'button', :class => 'close' %>
  </td>
</tr>

app/views/routes/create.html.erb
<h1>Routes#create</h1>
<p>Find me in app/views/routes/create.html.erb</p>

app/views/routes/destroy.html.erb
<h1>Routes#destroy</h1>
<p>Find me in app/views/routes/destroy.html.erb</p>

app/views/routes/edit.html.erb
<div id='surface-container'>
  <canvas id='surface'></canvas>
</div>

<div class='footbox'>
  <%= form_for @route do |f| %>
    <div class='footdiv' id='waypoints'>
      <h3>Waypoints</h3>
      <table>
      <thead>
        <tr><th>Name</th><th>Distance</th></tr>
      </thead>
      <tbody>
          <%= f.fields_for :waypoints do |wf| %>
            <% render :partial => 'waypoint', :locals => { :f => wf } %>
          <% end %>
        </tbody>
      </table>
      
      <%= add_child_link "Add Waypoint", :waypoints ,'btn btn-small' %></p>
      <%= new_child_fields_template f, :waypoints %>
    </div>
    <%= render partial: 'tools', :locals => { :f => f } %>
  <% end %>
</div>  
<div id='bottom-anchor'></div>

<script>
  var streams = <%= raw @route.streams %>;
  var waypoints = <%= raw @route.waypoints.to_json %>;
  var renderer_options = JSON.parse('<%= 
    if @route.renderer_options.to_s == ''
      "[]"
    else 
      raw @route.renderer_options
    end %>');
</script>

<div id='jstemplates'>
  <table>
    <%= yield :jstemplates %>
  </table>
  <%= render partial: 'image_save' %>
</div>
<div id='image-assets'>
  <%= image_tag("mesmeride-watermark.png", :id => 'watermark') %>
  <%= image_tag("mesmeride-watermark-small.png", :id => 'watermark-small') %>
  <%= image_tag("mesmeride-watermark-tiny.png", :id => 'watermark-tiny') %>
</div>

<!--  javascript_include_tag "giro_renderer", "data-turbolinks-track" => true  -->

app/views/routes/index.html.erb
<h1>Routes#index</h1>
<p>Find me in app/views/routes/index.html.erb</p>

app/views/routes/new.html.erb
<div style='display:none'>
<%= form_for @route do |f| %>
<%=   f.hidden_field(:source) %>
<%=   f.hidden_field(:source_id) %>
<%=   f.submit("Import Route") %>
<% end %>
</div>
<h3>Please wait while importing route...</h3>

app/views/routes/show.html.erb
<h1>Routes#show</h1>
<p>Find me in app/views/routes/show.html.erb</p>

app/views/routes/update.html.erb
<h1>Routes#update</h1>
<p>Find me in app/views/routes/update.html.erb</p>