config/routes.rb
Mesmeride::Application.routes.draw do

  match '/auth/:provider/callback', :to => 'sessions#create', via: 'get'
  root 'static_pages#home'
  resources :sessions, only: [:create, :destroy]
  resources :strava_activities, only: [:create]
  resources :routes do
    resources :waypoints, only: [:index, :create, :destroy]
  end
  resources :route_images, only: [:show, :destroy]

  match '/route_images/:id/download', :to => 'route_images#download', via: 'get'
  
  match '/routes/:id/image_save', :to => 'routes#image_save', via: 'post'
  match '/routes/:id/image_permalink', :to => 'routes#image_permalink', via: 'post'
  
  match '/get_activity',  to: 'strava_activities#new', via: 'get'
  
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signin',  to: 'static_pages#signin', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/fb_channel', to: 'static_pages#fb_channel', via: 'get'
  

  

end

app/views/layouts/_facebook.html.erb
<div id="fb-root"></div>
<script>
  window.fbAsyncInit = function() {
    // init the FB JS SDK
    FB.init({
      appId      : '509948949097122',                        // App ID from the app dashboard
      channelUrl : '<%=  url_for(:action => 'fb_channel', :controller => 'static_pages', :only_path => false) %>', // Channel file for x-domain comms
      status     : false,                                 // Check Facebook Login status
      xfbml      : false                                  // Look for social plugins on the page
    });

    // Additional initialization code such as adding Event Listeners goes here
  };

  // Load the SDK asynchronously
  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/all.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://www.mesmeride.com/">Mesmeride</a>
    by <a href='http://marc.durdin.net/' target='_blank'>Marc Durdin</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <!--<li><%= link_to "Contact", contact_path %></li>-->
      <li><a target='_blank' href="http://twitter.com/mesmeride">Twitter</a></li>
      <li><a target='_blank' href="http://facebook.com/mesmeride">Facebook</a></li>
    </ul>
  </nav>
</footer>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-6824567-3', 'mesmeride.com');
  ga('send', 'pageview');
</script>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to image_tag("logo-charcoal-40.png"), root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "Help",    help_path %></li>
          
          <% if signed_in? %>
            <li><%= link_to @current_user.name, '#' %></li>
            <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
      <%= image_tag("beta.png", :alt => "Beta", :class => 'beta') %>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_twitter.html.erb
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    
  </head>
  <body data-controller="<%= params[:controller] %>" data-action="<%= params[:action] %>">
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><!-- todo fix button -->
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= value %> 
        </div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
    
    <%= render 'layouts/facebook' %>
    <%= render 'layouts/twitter' %>

  </body>
</html>